version: "3.7"
  
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    restart: always
    command: npm run dev
    volumes: 
      - ./:/app
      - /app/node_modules
    ports:
      - 3000:3000
